import { SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.items.getAll.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Guard Shack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!!user && (
          <div>
            Hi, {user.user?.username} <SignOutButton />
          </div>
        )}
        <div>{data?.map((item) => <div key={item.id}>{item.label} </div>)}</div>
      </main>
    </>
  );
}
